### ISSUE TITLE
Unable to find variable require

### ISSUE THREAD

**Issue by donszek** [IjzerenHein/famous-flex-tabbar#2]
Hi, 

Good day! I successfully installed using
npm install famous-flex

However, when I tried to add tabbar following the tutorial
var TabBar = require('famous-flex/widgets/TabBar');

i got error. 

May I know what is the reason behind this?  I checked using browser safari and it says unable to find variable require. 

I am using phone gap. 

Many thanks

**Comment by IjzerenHein** [comment]
Which bundler are you using, browserify or webpack?

**Comment by donszek** [comment]
I am afraid I am not using any of them, at least now I know I need to use them?!

For famous, I do not use the 'require' function. My code is
var Engine = famous.core.Engine;
var Modifier = famous.core.Modifier;
var Transform = famous.core.Transform; 
... etc

Is there a way to use such notation without invoking the 'require' method? I am not familiar with webpack. I prefer to include in the js file directly.

Thank you in advance!

**Comment by IjzerenHein** [comment]
Quick question, is that famous engine v0.7.x that you are using?

**Comment by donszek** [comment]
I am not sure the version of the engine. But i downloaded as a sample seed project from one of the fame.us site. Can I just clarify the proper way to do it. 

Write a js file using the require as shown in the example, then browserify it into somefile.js then only include the final somefile,js into the index.html?

**Comment by IjzerenHein** [comment]
Well if you downloaded the seed from the current famo.us site, then it must be v0.7.x.

Unfortunately, famous-flex was created for the v0.3.x API of famo.us so it want work with your seed.
I am hard at work at the next version of famous-flex which will support v0.7.x but that is still in the works.

**Comment by donszek** [comment]
Oh no!!!!! I really like your famous-flex!! 

Is there any chance I can still download and use the v0.3.x api in order to be compatible with your famous-flex? Thanks

**Comment by IjzerenHein** [comment]
Hi! Yeah you can use this Starterkit:
https://github.com/IjzerenHein/famous-Starterkit

:)

**Comment by donszek** [comment]
For reference to anyone who wishes to use this fantastic modules but have no clues on how to use webpack:

Simply include in the global-flex.js into your file and you may refer to them using 
var TabBar = famousflex.widgets.TabBar; 
instead of
var TabBar = require('famous-flex/widgets/TabBar');

cheers.

**Comment by IjzerenHein** [comment]
:)
